/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitySlugRouteImport } from './routes/$citySlug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapMainDotxmlRouteImport } from './routes/sitemap-main[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as CitySlugIndexRouteImport } from './routes/$citySlug.index'
import { Route as CitySlugBuscarRouteImport } from './routes/$citySlug.buscar'
import { Route as CitySlugEventosRouteImport } from './routes/$citySlug.eventos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCadastrarEmpresaRouteImport } from './routes/_authenticated/cadastrar-empresa'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthTwoFactorRouteImport } from './routes/auth_.two-factor'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog.rss[.]xml'
import { Route as CheckoutRetornoRouteImport } from './routes/checkout.retorno'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as EmpresaIdRouteImport } from './routes/empresa.$id'
import { Route as EventosIdRouteImport } from './routes/eventos.$id'
import { Route as PreviewTokenRouteImport } from './routes/preview.$token'
import { Route as SitemapCitiesPageRouteImport } from './routes/sitemap-cities/$page'
import { Route as SitemapCompaniesPageRouteImport } from './routes/sitemap-companies/$page'
import { Route as SitemapNeighborhoodsPageRouteImport } from './routes/sitemap-neighborhoods/$page'
import { Route as SitemapProductsPageRouteImport } from './routes/sitemap-products.$page'
import { Route as SuporteRedefinir2faRouteImport } from './routes/suporte.redefinir-2fa'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as CitySlugBairroBairroSlugRouteImport } from './routes/$citySlug.bairro.$bairroSlug'
import { Route as CitySlugCategoriaCatSlugRouteImport } from './routes/$citySlug.categoria.$catSlug'
import { Route as CitySlugEmpresaCompSlugRouteImport } from './routes/$citySlug.empresa.$compSlug'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner.index'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelAvaliacoesRouteImport } from './routes/_authenticated/painel.avaliacoes'
import { Route as AuthenticatedPainelConfiguracoesRouteImport } from './routes/_authenticated/painel.configuracoes'
import { Route as AuthenticatedPainelSegurancaRouteImport } from './routes/_authenticated/painel.seguranca'
import { Route as ApiPublicContactSubmitRouteImport } from './routes/api/public/contact-submit'
import { Route as BlogCategoriaSlugRouteImport } from './routes/blog.categoria.$slug'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicHooksNotificationEmailRouteImport } from './routes/api/public/hooks/notification-email'
import { Route as ApiPublicHooksRetryEmailDlqRouteImport } from './routes/api/public/hooks/retry-email-dlq'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push.dispatch'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as AuthenticatedOwnerEmpresaIdDashboardRouteImport } from './routes/_authenticated/owner.empresa.$id.dashboard'
import { Route as AuthenticatedOwnerEmpresaIdDestaqueRouteImport } from './routes/_authenticated/owner.empresa.$id.destaque'
import { Route as AuthenticatedOwnerEmpresaIdEditarRouteImport } from './routes/_authenticated/owner.empresa.$id.editar'
import { Route as AuthenticatedOwnerEmpresaIdEventosRouteImport } from './routes/_authenticated/owner.empresa.$id.eventos'
import { Route as AuthenticatedOwnerEmpresaIdProdutosRouteImport } from './routes/_authenticated/owner.empresa.$id.produtos'
import { Route as ApiPublicOgEventIdRouteImport } from './routes/api/public/og.event.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/$citySlug',
  path: '/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapMainDotxmlRoute = SitemapMainDotxmlRouteImport.update({
  id: '/sitemap-main.xml',
  path: '/sitemap-main.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugIndexRoute = CitySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitySlugRoute,
} as any)
const CitySlugBuscarRoute = CitySlugBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => CitySlugRoute,
} as any)
const CitySlugEventosRoute = CitySlugEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => CitySlugRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrarEmpresaRoute =
  AuthenticatedCadastrarEmpresaRouteImport.update({
    id: '/cadastrar-empresa',
    path: '/cadastrar-empresa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/auth_/two-factor',
  path: '/auth/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => BlogRoute,
} as any)
const CheckoutRetornoRoute = CheckoutRetornoRouteImport.update({
  id: '/checkout/retorno',
  path: '/checkout/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaIdRoute = EmpresaIdRouteImport.update({
  id: '/empresa/$id',
  path: '/empresa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIdRoute = EventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCitiesPageRoute = SitemapCitiesPageRouteImport.update({
  id: '/sitemap-cities/$page',
  path: '/sitemap-cities/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCompaniesPageRoute = SitemapCompaniesPageRouteImport.update({
  id: '/sitemap-companies/$page',
  path: '/sitemap-companies/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapNeighborhoodsPageRoute =
  SitemapNeighborhoodsPageRouteImport.update({
    id: '/sitemap-neighborhoods/$page',
    path: '/sitemap-neighborhoods/$page',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapProductsPageRoute = SitemapProductsPageRouteImport.update({
  id: '/sitemap-products/$page',
  path: '/sitemap-products/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRedefinir2faRoute = SuporteRedefinir2faRouteImport.update({
  id: '/suporte/redefinir-2fa',
  path: '/suporte/redefinir-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugBairroBairroSlugRoute =
  CitySlugBairroBairroSlugRouteImport.update({
    id: '/bairro/$bairroSlug',
    path: '/bairro/$bairroSlug',
    getParentRoute: () => CitySlugRoute,
  } as any)
const CitySlugCategoriaCatSlugRoute =
  CitySlugCategoriaCatSlugRouteImport.update({
    id: '/categoria/$catSlug',
    path: '/categoria/$catSlug',
    getParentRoute: () => CitySlugRoute,
  } as any)
const CitySlugEmpresaCompSlugRoute = CitySlugEmpresaCompSlugRouteImport.update({
  id: '/empresa/$compSlug',
  path: '/empresa/$compSlug',
  getParentRoute: () => CitySlugRoute,
} as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAvaliacoesRoute =
  AuthenticatedPainelAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelConfiguracoesRoute =
  AuthenticatedPainelConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelSegurancaRoute =
  AuthenticatedPainelSegurancaRouteImport.update({
    id: '/seguranca',
    path: '/seguranca',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const ApiPublicContactSubmitRoute = ApiPublicContactSubmitRouteImport.update({
  id: '/api/public/contact-submit',
  path: '/api/public/contact-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoriaSlugRoute = BlogCategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotificationEmailRoute =
  ApiPublicHooksNotificationEmailRouteImport.update({
    id: '/api/public/hooks/notification-email',
    path: '/api/public/hooks/notification-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRetryEmailDlqRoute =
  ApiPublicHooksRetryEmailDlqRouteImport.update({
    id: '/api/public/hooks/retry-email-dlq',
    path: '/api/public/hooks/retry-email-dlq',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push/dispatch',
  path: '/api/public/push/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOwnerEmpresaIdDashboardRoute =
  AuthenticatedOwnerEmpresaIdDashboardRouteImport.update({
    id: '/owner/empresa/$id/dashboard',
    path: '/owner/empresa/$id/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerEmpresaIdDestaqueRoute =
  AuthenticatedOwnerEmpresaIdDestaqueRouteImport.update({
    id: '/owner/empresa/$id/destaque',
    path: '/owner/empresa/$id/destaque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerEmpresaIdEditarRoute =
  AuthenticatedOwnerEmpresaIdEditarRouteImport.update({
    id: '/owner/empresa/$id/editar',
    path: '/owner/empresa/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerEmpresaIdEventosRoute =
  AuthenticatedOwnerEmpresaIdEventosRouteImport.update({
    id: '/owner/empresa/$id/eventos',
    path: '/owner/empresa/$id/eventos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerEmpresaIdProdutosRoute =
  AuthenticatedOwnerEmpresaIdProdutosRouteImport.update({
    id: '/owner/empresa/$id/produtos',
    path: '/owner/empresa/$id/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicOgEventIdRoute = ApiPublicOgEventIdRouteImport.update({
  id: '/api/public/og/event/$id',
  path: '/api/public/og/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-main.xml': typeof SitemapMainDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRoute
  '/$citySlug/buscar': typeof CitySlugBuscarRoute
  '/$citySlug/eventos': typeof CitySlugEventosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cadastrar-empresa': typeof AuthenticatedCadastrarEmpresaRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/eventos/$id': typeof EventosIdRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/sitemap-cities/$page': typeof SitemapCitiesPageRoute
  '/sitemap-companies/$page': typeof SitemapCompaniesPageRoute
  '/sitemap-neighborhoods/$page': typeof SitemapNeighborhoodsPageRoute
  '/sitemap-products/$page': typeof SitemapProductsPageRoute
  '/suporte/redefinir-2fa': typeof SuporteRedefinir2faRoute
  '/u/$handle': typeof UHandleRoute
  '/$citySlug/': typeof CitySlugIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$citySlug/bairro/$bairroSlug': typeof CitySlugBairroBairroSlugRoute
  '/$citySlug/categoria/$catSlug': typeof CitySlugCategoriaCatSlugRoute
  '/$citySlug/empresa/$compSlug': typeof CitySlugEmpresaCompSlugRoute
  '/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/seguranca': typeof AuthenticatedPainelSegurancaRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/notification-email': typeof ApiPublicHooksNotificationEmailRoute
  '/api/public/hooks/retry-email-dlq': typeof ApiPublicHooksRetryEmailDlqRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/owner/empresa/$id/dashboard': typeof AuthenticatedOwnerEmpresaIdDashboardRoute
  '/owner/empresa/$id/destaque': typeof AuthenticatedOwnerEmpresaIdDestaqueRoute
  '/owner/empresa/$id/editar': typeof AuthenticatedOwnerEmpresaIdEditarRoute
  '/owner/empresa/$id/eventos': typeof AuthenticatedOwnerEmpresaIdEventosRoute
  '/owner/empresa/$id/produtos': typeof AuthenticatedOwnerEmpresaIdProdutosRoute
  '/api/public/og/event/$id': typeof ApiPublicOgEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-main.xml': typeof SitemapMainDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRoute
  '/$citySlug/buscar': typeof CitySlugBuscarRoute
  '/$citySlug/eventos': typeof CitySlugEventosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cadastrar-empresa': typeof AuthenticatedCadastrarEmpresaRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/eventos/$id': typeof EventosIdRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/sitemap-cities/$page': typeof SitemapCitiesPageRoute
  '/sitemap-companies/$page': typeof SitemapCompaniesPageRoute
  '/sitemap-neighborhoods/$page': typeof SitemapNeighborhoodsPageRoute
  '/sitemap-products/$page': typeof SitemapProductsPageRoute
  '/suporte/redefinir-2fa': typeof SuporteRedefinir2faRoute
  '/u/$handle': typeof UHandleRoute
  '/$citySlug': typeof CitySlugIndexRoute
  '/blog': typeof BlogIndexRoute
  '/$citySlug/bairro/$bairroSlug': typeof CitySlugBairroBairroSlugRoute
  '/$citySlug/categoria/$catSlug': typeof CitySlugCategoriaCatSlugRoute
  '/$citySlug/empresa/$compSlug': typeof CitySlugEmpresaCompSlugRoute
  '/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/seguranca': typeof AuthenticatedPainelSegurancaRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/notification-email': typeof ApiPublicHooksNotificationEmailRoute
  '/api/public/hooks/retry-email-dlq': typeof ApiPublicHooksRetryEmailDlqRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/owner/empresa/$id/dashboard': typeof AuthenticatedOwnerEmpresaIdDashboardRoute
  '/owner/empresa/$id/destaque': typeof AuthenticatedOwnerEmpresaIdDestaqueRoute
  '/owner/empresa/$id/editar': typeof AuthenticatedOwnerEmpresaIdEditarRoute
  '/owner/empresa/$id/eventos': typeof AuthenticatedOwnerEmpresaIdEventosRoute
  '/owner/empresa/$id/produtos': typeof AuthenticatedOwnerEmpresaIdProdutosRoute
  '/api/public/og/event/$id': typeof ApiPublicOgEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$citySlug': typeof CitySlugRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap-main.xml': typeof SitemapMainDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRoute
  '/$citySlug/buscar': typeof CitySlugBuscarRoute
  '/$citySlug/eventos': typeof CitySlugEventosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cadastrar-empresa': typeof AuthenticatedCadastrarEmpresaRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/auth_/two-factor': typeof AuthTwoFactorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/eventos/$id': typeof EventosIdRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/sitemap-cities/$page': typeof SitemapCitiesPageRoute
  '/sitemap-companies/$page': typeof SitemapCompaniesPageRoute
  '/sitemap-neighborhoods/$page': typeof SitemapNeighborhoodsPageRoute
  '/sitemap-products/$page': typeof SitemapProductsPageRoute
  '/suporte/redefinir-2fa': typeof SuporteRedefinir2faRoute
  '/u/$handle': typeof UHandleRoute
  '/$citySlug/': typeof CitySlugIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$citySlug/bairro/$bairroSlug': typeof CitySlugBairroBairroSlugRoute
  '/$citySlug/categoria/$catSlug': typeof CitySlugCategoriaCatSlugRoute
  '/$citySlug/empresa/$compSlug': typeof CitySlugEmpresaCompSlugRoute
  '/_authenticated/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/_authenticated/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/_authenticated/painel/seguranca': typeof AuthenticatedPainelSegurancaRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/notification-email': typeof ApiPublicHooksNotificationEmailRoute
  '/api/public/hooks/retry-email-dlq': typeof ApiPublicHooksRetryEmailDlqRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/owner/empresa/$id/dashboard': typeof AuthenticatedOwnerEmpresaIdDashboardRoute
  '/_authenticated/owner/empresa/$id/destaque': typeof AuthenticatedOwnerEmpresaIdDestaqueRoute
  '/_authenticated/owner/empresa/$id/editar': typeof AuthenticatedOwnerEmpresaIdEditarRoute
  '/_authenticated/owner/empresa/$id/eventos': typeof AuthenticatedOwnerEmpresaIdEventosRoute
  '/_authenticated/owner/empresa/$id/produtos': typeof AuthenticatedOwnerEmpresaIdProdutosRoute
  '/api/public/og/event/$id': typeof ApiPublicOgEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$citySlug'
    | '/auth'
    | '/blog'
    | '/buscar'
    | '/contato'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap-main.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/vendas'
    | '/$citySlug/buscar'
    | '/$citySlug/eventos'
    | '/admin'
    | '/cadastrar-empresa'
    | '/favoritos'
    | '/notificacoes'
    | '/painel'
    | '/auth/two-factor'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/checkout/retorno'
    | '/email/unsubscribe'
    | '/empresa/$id'
    | '/eventos/$id'
    | '/preview/$token'
    | '/sitemap-cities/$page'
    | '/sitemap-companies/$page'
    | '/sitemap-neighborhoods/$page'
    | '/sitemap-products/$page'
    | '/suporte/redefinir-2fa'
    | '/u/$handle'
    | '/$citySlug/'
    | '/blog/'
    | '/$citySlug/bairro/$bairroSlug'
    | '/$citySlug/categoria/$catSlug'
    | '/$citySlug/empresa/$compSlug'
    | '/painel/avaliacoes'
    | '/painel/configuracoes'
    | '/painel/seguranca'
    | '/api/public/contact-submit'
    | '/blog/categoria/$slug'
    | '/lovable/email/suppression'
    | '/owner/'
    | '/painel/'
    | '/api/public/hooks/notification-email'
    | '/api/public/hooks/retry-email-dlq'
    | '/api/public/payments/webhook'
    | '/api/public/push/dispatch'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/owner/empresa/$id/dashboard'
    | '/owner/empresa/$id/destaque'
    | '/owner/empresa/$id/editar'
    | '/owner/empresa/$id/eventos'
    | '/owner/empresa/$id/produtos'
    | '/api/public/og/event/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap-main.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/vendas'
    | '/$citySlug/buscar'
    | '/$citySlug/eventos'
    | '/admin'
    | '/cadastrar-empresa'
    | '/favoritos'
    | '/notificacoes'
    | '/auth/two-factor'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/checkout/retorno'
    | '/email/unsubscribe'
    | '/empresa/$id'
    | '/eventos/$id'
    | '/preview/$token'
    | '/sitemap-cities/$page'
    | '/sitemap-companies/$page'
    | '/sitemap-neighborhoods/$page'
    | '/sitemap-products/$page'
    | '/suporte/redefinir-2fa'
    | '/u/$handle'
    | '/$citySlug'
    | '/blog'
    | '/$citySlug/bairro/$bairroSlug'
    | '/$citySlug/categoria/$catSlug'
    | '/$citySlug/empresa/$compSlug'
    | '/painel/avaliacoes'
    | '/painel/configuracoes'
    | '/painel/seguranca'
    | '/api/public/contact-submit'
    | '/blog/categoria/$slug'
    | '/lovable/email/suppression'
    | '/owner'
    | '/painel'
    | '/api/public/hooks/notification-email'
    | '/api/public/hooks/retry-email-dlq'
    | '/api/public/payments/webhook'
    | '/api/public/push/dispatch'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/owner/empresa/$id/dashboard'
    | '/owner/empresa/$id/destaque'
    | '/owner/empresa/$id/editar'
    | '/owner/empresa/$id/eventos'
    | '/owner/empresa/$id/produtos'
    | '/api/public/og/event/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$citySlug'
    | '/auth'
    | '/blog'
    | '/buscar'
    | '/contato'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap-main.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/vendas'
    | '/$citySlug/buscar'
    | '/$citySlug/eventos'
    | '/_authenticated/admin'
    | '/_authenticated/cadastrar-empresa'
    | '/_authenticated/favoritos'
    | '/_authenticated/notificacoes'
    | '/_authenticated/painel'
    | '/auth_/two-factor'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/checkout/retorno'
    | '/email/unsubscribe'
    | '/empresa/$id'
    | '/eventos/$id'
    | '/preview/$token'
    | '/sitemap-cities/$page'
    | '/sitemap-companies/$page'
    | '/sitemap-neighborhoods/$page'
    | '/sitemap-products/$page'
    | '/suporte/redefinir-2fa'
    | '/u/$handle'
    | '/$citySlug/'
    | '/blog/'
    | '/$citySlug/bairro/$bairroSlug'
    | '/$citySlug/categoria/$catSlug'
    | '/$citySlug/empresa/$compSlug'
    | '/_authenticated/painel/avaliacoes'
    | '/_authenticated/painel/configuracoes'
    | '/_authenticated/painel/seguranca'
    | '/api/public/contact-submit'
    | '/blog/categoria/$slug'
    | '/lovable/email/suppression'
    | '/_authenticated/owner/'
    | '/_authenticated/painel/'
    | '/api/public/hooks/notification-email'
    | '/api/public/hooks/retry-email-dlq'
    | '/api/public/payments/webhook'
    | '/api/public/push/dispatch'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/owner/empresa/$id/dashboard'
    | '/_authenticated/owner/empresa/$id/destaque'
    | '/_authenticated/owner/empresa/$id/editar'
    | '/_authenticated/owner/empresa/$id/eventos'
    | '/_authenticated/owner/empresa/$id/produtos'
    | '/api/public/og/event/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CitySlugRoute: typeof CitySlugRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  ContatoRoute: typeof ContatoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapMainDotxmlRoute: typeof SitemapMainDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  VendasRoute: typeof VendasRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  CheckoutRetornoRoute: typeof CheckoutRetornoRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EmpresaIdRoute: typeof EmpresaIdRoute
  EventosIdRoute: typeof EventosIdRoute
  PreviewTokenRoute: typeof PreviewTokenRoute
  SitemapCitiesPageRoute: typeof SitemapCitiesPageRoute
  SitemapCompaniesPageRoute: typeof SitemapCompaniesPageRoute
  SitemapNeighborhoodsPageRoute: typeof SitemapNeighborhoodsPageRoute
  SitemapProductsPageRoute: typeof SitemapProductsPageRoute
  SuporteRedefinir2faRoute: typeof SuporteRedefinir2faRoute
  UHandleRoute: typeof UHandleRoute
  ApiPublicContactSubmitRoute: typeof ApiPublicContactSubmitRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksNotificationEmailRoute: typeof ApiPublicHooksNotificationEmailRoute
  ApiPublicHooksRetryEmailDlqRoute: typeof ApiPublicHooksRetryEmailDlqRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicOgEventIdRoute: typeof ApiPublicOgEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$citySlug': {
      id: '/$citySlug'
      path: '/$citySlug'
      fullPath: '/$citySlug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-main.xml': {
      id: '/sitemap-main.xml'
      path: '/sitemap-main.xml'
      fullPath: '/sitemap-main.xml'
      preLoaderRoute: typeof SitemapMainDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$citySlug/': {
      id: '/$citySlug/'
      path: '/'
      fullPath: '/$citySlug/'
      preLoaderRoute: typeof CitySlugIndexRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/$citySlug/buscar': {
      id: '/$citySlug/buscar'
      path: '/buscar'
      fullPath: '/$citySlug/buscar'
      preLoaderRoute: typeof CitySlugBuscarRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/$citySlug/eventos': {
      id: '/$citySlug/eventos'
      path: '/eventos'
      fullPath: '/$citySlug/eventos'
      preLoaderRoute: typeof CitySlugEventosRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastrar-empresa': {
      id: '/_authenticated/cadastrar-empresa'
      path: '/cadastrar-empresa'
      fullPath: '/cadastrar-empresa'
      preLoaderRoute: typeof AuthenticatedCadastrarEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/two-factor': {
      id: '/auth_/two-factor'
      path: '/auth/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof BlogRoute
    }
    '/checkout/retorno': {
      id: '/checkout/retorno'
      path: '/checkout/retorno'
      fullPath: '/checkout/retorno'
      preLoaderRoute: typeof CheckoutRetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$id': {
      id: '/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/empresa/$id'
      preLoaderRoute: typeof EmpresaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$id': {
      id: '/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof EventosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$token': {
      id: '/preview/$token'
      path: '/preview/$token'
      fullPath: '/preview/$token'
      preLoaderRoute: typeof PreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-cities/$page': {
      id: '/sitemap-cities/$page'
      path: '/sitemap-cities/$page'
      fullPath: '/sitemap-cities/$page'
      preLoaderRoute: typeof SitemapCitiesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-companies/$page': {
      id: '/sitemap-companies/$page'
      path: '/sitemap-companies/$page'
      fullPath: '/sitemap-companies/$page'
      preLoaderRoute: typeof SitemapCompaniesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-neighborhoods/$page': {
      id: '/sitemap-neighborhoods/$page'
      path: '/sitemap-neighborhoods/$page'
      fullPath: '/sitemap-neighborhoods/$page'
      preLoaderRoute: typeof SitemapNeighborhoodsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-products/$page': {
      id: '/sitemap-products/$page'
      path: '/sitemap-products/$page'
      fullPath: '/sitemap-products/$page'
      preLoaderRoute: typeof SitemapProductsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte/redefinir-2fa': {
      id: '/suporte/redefinir-2fa'
      path: '/suporte/redefinir-2fa'
      fullPath: '/suporte/redefinir-2fa'
      preLoaderRoute: typeof SuporteRedefinir2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$citySlug/bairro/$bairroSlug': {
      id: '/$citySlug/bairro/$bairroSlug'
      path: '/bairro/$bairroSlug'
      fullPath: '/$citySlug/bairro/$bairroSlug'
      preLoaderRoute: typeof CitySlugBairroBairroSlugRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/$citySlug/categoria/$catSlug': {
      id: '/$citySlug/categoria/$catSlug'
      path: '/categoria/$catSlug'
      fullPath: '/$citySlug/categoria/$catSlug'
      preLoaderRoute: typeof CitySlugCategoriaCatSlugRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/$citySlug/empresa/$compSlug': {
      id: '/$citySlug/empresa/$compSlug'
      path: '/empresa/$compSlug'
      fullPath: '/$citySlug/empresa/$compSlug'
      preLoaderRoute: typeof CitySlugEmpresaCompSlugRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/avaliacoes': {
      id: '/_authenticated/painel/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/painel/avaliacoes'
      preLoaderRoute: typeof AuthenticatedPainelAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/configuracoes': {
      id: '/_authenticated/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof AuthenticatedPainelConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/seguranca': {
      id: '/_authenticated/painel/seguranca'
      path: '/seguranca'
      fullPath: '/painel/seguranca'
      preLoaderRoute: typeof AuthenticatedPainelSegurancaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/api/public/contact-submit': {
      id: '/api/public/contact-submit'
      path: '/api/public/contact-submit'
      fullPath: '/api/public/contact-submit'
      preLoaderRoute: typeof ApiPublicContactSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/categoria/$slug': {
      id: '/blog/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/blog/categoria/$slug'
      preLoaderRoute: typeof BlogCategoriaSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notification-email': {
      id: '/api/public/hooks/notification-email'
      path: '/api/public/hooks/notification-email'
      fullPath: '/api/public/hooks/notification-email'
      preLoaderRoute: typeof ApiPublicHooksNotificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/retry-email-dlq': {
      id: '/api/public/hooks/retry-email-dlq'
      path: '/api/public/hooks/retry-email-dlq'
      fullPath: '/api/public/hooks/retry-email-dlq'
      preLoaderRoute: typeof ApiPublicHooksRetryEmailDlqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/dispatch': {
      id: '/api/public/push/dispatch'
      path: '/api/public/push/dispatch'
      fullPath: '/api/public/push/dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner/empresa/$id/dashboard': {
      id: '/_authenticated/owner/empresa/$id/dashboard'
      path: '/owner/empresa/$id/dashboard'
      fullPath: '/owner/empresa/$id/dashboard'
      preLoaderRoute: typeof AuthenticatedOwnerEmpresaIdDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/empresa/$id/destaque': {
      id: '/_authenticated/owner/empresa/$id/destaque'
      path: '/owner/empresa/$id/destaque'
      fullPath: '/owner/empresa/$id/destaque'
      preLoaderRoute: typeof AuthenticatedOwnerEmpresaIdDestaqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/empresa/$id/editar': {
      id: '/_authenticated/owner/empresa/$id/editar'
      path: '/owner/empresa/$id/editar'
      fullPath: '/owner/empresa/$id/editar'
      preLoaderRoute: typeof AuthenticatedOwnerEmpresaIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/empresa/$id/eventos': {
      id: '/_authenticated/owner/empresa/$id/eventos'
      path: '/owner/empresa/$id/eventos'
      fullPath: '/owner/empresa/$id/eventos'
      preLoaderRoute: typeof AuthenticatedOwnerEmpresaIdEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/empresa/$id/produtos': {
      id: '/_authenticated/owner/empresa/$id/produtos'
      path: '/owner/empresa/$id/produtos'
      fullPath: '/owner/empresa/$id/produtos'
      preLoaderRoute: typeof AuthenticatedOwnerEmpresaIdProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/og/event/$id': {
      id: '/api/public/og/event/$id'
      path: '/api/public/og/event/$id'
      fullPath: '/api/public/og/event/$id'
      preLoaderRoute: typeof ApiPublicOgEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelAvaliacoesRoute: typeof AuthenticatedPainelAvaliacoesRoute
  AuthenticatedPainelConfiguracoesRoute: typeof AuthenticatedPainelConfiguracoesRoute
  AuthenticatedPainelSegurancaRoute: typeof AuthenticatedPainelSegurancaRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelAvaliacoesRoute: AuthenticatedPainelAvaliacoesRoute,
  AuthenticatedPainelConfiguracoesRoute: AuthenticatedPainelConfiguracoesRoute,
  AuthenticatedPainelSegurancaRoute: AuthenticatedPainelSegurancaRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCadastrarEmpresaRoute: typeof AuthenticatedCadastrarEmpresaRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
  AuthenticatedOwnerEmpresaIdDashboardRoute: typeof AuthenticatedOwnerEmpresaIdDashboardRoute
  AuthenticatedOwnerEmpresaIdDestaqueRoute: typeof AuthenticatedOwnerEmpresaIdDestaqueRoute
  AuthenticatedOwnerEmpresaIdEditarRoute: typeof AuthenticatedOwnerEmpresaIdEditarRoute
  AuthenticatedOwnerEmpresaIdEventosRoute: typeof AuthenticatedOwnerEmpresaIdEventosRoute
  AuthenticatedOwnerEmpresaIdProdutosRoute: typeof AuthenticatedOwnerEmpresaIdProdutosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCadastrarEmpresaRoute: AuthenticatedCadastrarEmpresaRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
  AuthenticatedOwnerEmpresaIdDashboardRoute:
    AuthenticatedOwnerEmpresaIdDashboardRoute,
  AuthenticatedOwnerEmpresaIdDestaqueRoute:
    AuthenticatedOwnerEmpresaIdDestaqueRoute,
  AuthenticatedOwnerEmpresaIdEditarRoute:
    AuthenticatedOwnerEmpresaIdEditarRoute,
  AuthenticatedOwnerEmpresaIdEventosRoute:
    AuthenticatedOwnerEmpresaIdEventosRoute,
  AuthenticatedOwnerEmpresaIdProdutosRoute:
    AuthenticatedOwnerEmpresaIdProdutosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CitySlugRouteChildren {
  CitySlugBuscarRoute: typeof CitySlugBuscarRoute
  CitySlugEventosRoute: typeof CitySlugEventosRoute
  CitySlugIndexRoute: typeof CitySlugIndexRoute
  CitySlugBairroBairroSlugRoute: typeof CitySlugBairroBairroSlugRoute
  CitySlugCategoriaCatSlugRoute: typeof CitySlugCategoriaCatSlugRoute
  CitySlugEmpresaCompSlugRoute: typeof CitySlugEmpresaCompSlugRoute
}

const CitySlugRouteChildren: CitySlugRouteChildren = {
  CitySlugBuscarRoute: CitySlugBuscarRoute,
  CitySlugEventosRoute: CitySlugEventosRoute,
  CitySlugIndexRoute: CitySlugIndexRoute,
  CitySlugBairroBairroSlugRoute: CitySlugBairroBairroSlugRoute,
  CitySlugCategoriaCatSlugRoute: CitySlugCategoriaCatSlugRoute,
  CitySlugEmpresaCompSlugRoute: CitySlugEmpresaCompSlugRoute,
}

const CitySlugRouteWithChildren = CitySlugRoute._addFileChildren(
  CitySlugRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategoriaSlugRoute: typeof BlogCategoriaSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategoriaSlugRoute: BlogCategoriaSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CitySlugRoute: CitySlugRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  BuscarRoute: BuscarRoute,
  ContatoRoute: ContatoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapMainDotxmlRoute: SitemapMainDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  VendasRoute: VendasRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  CheckoutRetornoRoute: CheckoutRetornoRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EmpresaIdRoute: EmpresaIdRoute,
  EventosIdRoute: EventosIdRoute,
  PreviewTokenRoute: PreviewTokenRoute,
  SitemapCitiesPageRoute: SitemapCitiesPageRoute,
  SitemapCompaniesPageRoute: SitemapCompaniesPageRoute,
  SitemapNeighborhoodsPageRoute: SitemapNeighborhoodsPageRoute,
  SitemapProductsPageRoute: SitemapProductsPageRoute,
  SuporteRedefinir2faRoute: SuporteRedefinir2faRoute,
  UHandleRoute: UHandleRoute,
  ApiPublicContactSubmitRoute: ApiPublicContactSubmitRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksNotificationEmailRoute: ApiPublicHooksNotificationEmailRoute,
  ApiPublicHooksRetryEmailDlqRoute: ApiPublicHooksRetryEmailDlqRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicOgEventIdRoute: ApiPublicOgEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
